easy_admin:
    entities:
#        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            list:
                fields: ['id', 'username', 'mail', 'amount', 'games', 'roles', 'next_bet']
        Comment:
            class: App\Entity\Comment

        Article:
            class: App\Entity\Article

        Game:
            class: App\Entity\Game

