version: "3.6"

services:
    app:
        volumes:
            - "~/.composer:/home/app/.composer"

    nginx:
        ports:
            - "8082:80"

    db:
        ports:
            - "3308:3306"
