<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.eusJIZx' shared service.

return $this->privates['.service_locator.eusJIZx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService.php', true],
], [
    'articleRepository' => 'App\\Repository\\ArticleRepository',
]);
