<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.o92VhBt' shared service.

return $this->privates['.service_locator.o92VhBt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'feedIo' => ['services', 'feedio', 'getFeedioService.php', true],
    'provider' => ['privates', 'debril.rss_atom.provider', 'getDebril_RssAtom_ProviderService.php', true],
], [
    'feedIo' => '?',
    'provider' => '?',
]);
