<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7AkOzGK' shared service.

return $this->privates['.service_locator.7AkOzGK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService.php', true],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'gameRepository' => 'App\\Repository\\GameRepository',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
