<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debril.rss_atom.provider' shared service.

include_once $this->targetDirs[3].'/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Provider/FeedContentProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Provider/MockProvider.php';

return $this->privates['debril.rss_atom.provider'] = new \Debril\RssAtomBundle\Provider\MockProvider();
