<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'easyadmin.form.type.configurator.type' shared service.

include_once $this->targetDirs[3].'/vendor/easycorp/easyadmin-bundle/src/Form/Type/Configurator/TypeConfiguratorInterface.php';
include_once $this->targetDirs[3].'/vendor/easycorp/easyadmin-bundle/src/Form/Type/Configurator/TypeConfigurator.php';

return $this->privates['easyadmin.form.type.configurator.type'] = new \EasyCorp\Bundle\EasyAdminBundle\Form\Type\Configurator\TypeConfigurator(($this->services['easyadmin.config.manager'] ?? $this->getEasyadmin_Config_ManagerService()));
