<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'feedio' shared service.

include_once $this->targetDirs[3].'/vendor/debril/feed-io/src/FeedIo/FeedIo.php';
include_once $this->targetDirs[3].'/vendor/debril/feed-io/src/FeedIo/Adapter/ClientInterface.php';
include_once $this->targetDirs[3].'/vendor/debril/feed-io/src/FeedIo/Adapter/Guzzle/Client.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/Client.php';

$this->services['feedio'] = $instance = new \FeedIo\FeedIo(new \FeedIo\Adapter\Guzzle\Client(new \GuzzleHttp\Client()), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));

$instance->addDateFormats($this->parameters['debril_rss_atom.date_formats']);

return $instance;
