<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debril.rss_atom.provider' shared service.

return $this->privates['debril.rss_atom.provider'] = new \Debril\RssAtomBundle\Provider\MockProvider();
