<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'easyadmin.filter.type.decimal' shared service.

return $this->privates['easyadmin.filter.type.decimal'] = new \EasyCorp\Bundle\EasyAdminBundle\Form\Filter\Type\ComparisonFilterType('Symfony\\Component\\Form\\Extension\\Core\\Type\\NumberType', ['input' => 'string']);
