<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'easyadmin.filter.type.text' shared service.

return $this->privates['easyadmin.filter.type.text'] = new \EasyCorp\Bundle\EasyAdminBundle\Form\Filter\Type\TextFilterType();
