<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'easyadmin.filter.type.dateinterval' shared service.

return $this->privates['easyadmin.filter.type.dateinterval'] = new \EasyCorp\Bundle\EasyAdminBundle\Form\Filter\Type\ComparisonFilterType('Symfony\\Component\\Form\\Extension\\Core\\Type\\DateIntervalType', [], '', ['type' => 'datetime']);
