<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'easyadmin.form.type.batch' shared service.

return $this->privates['easyadmin.form.type.batch'] = new \EasyCorp\Bundle\EasyAdminBundle\Form\Type\EasyAdminBatchFormType(($this->services['easyadmin.config.manager'] ?? $this->getEasyadmin_Config_ManagerService()));
