<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fidry_alice_data_fixtures.loader.simple' shared service.

return new \Fidry\AliceDataFixtures\Loader\SimpleLoader(($this->services['nelmio_alice.files_loader'] ?? $this->load('getNelmioAlice_FilesLoaderService.php')), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
