<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fidry_alice_data_fixtures.loader.doctrine' shared service.

return $this->services['fidry_alice_data_fixtures.loader.doctrine'] = new \Fidry\AliceDataFixtures\Loader\PurgerLoader(($this->privates['fidry_alice_data_fixtures.doctrine.persister_loader'] ?? $this->load('getFidryAliceDataFixtures_Doctrine_PersisterLoaderService.php')), ($this->services['fidry_alice_data_fixtures.persistence.purger_factory.doctrine'] ?? $this->load('getFidryAliceDataFixtures_Persistence_PurgerFactory_DoctrineService.php')), 'delete', ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
