<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Debril\RssAtomBundle\Controller\StreamController' shared service.

return $this->services['Debril\\RssAtomBundle\\Controller\\StreamController'] = new \Debril\RssAtomBundle\Controller\StreamController();
