<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH3XEQAf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH3XEQAf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH3XEQAf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH3XEQAf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerH3XEQAf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'H3XEQAf',
    'container.build_id' => 'a561c849',
    'container.build_time' => 1561360523,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH3XEQAf');
